config/routes.rb
UsersMoydCo::Application.routes.draw do

  get  'oauth2/authorize'
  post 'oauth2/authorize'
  get  'oauth2/deny_authorize'
  get  'oauth2/allow_authorize'
  post 'oauth2/token',  to: 'oauth2#token_request'
  post 'oauth2/revoke'

  match 'checks/credit', to: 'checks#credit', via: [:options]
  match 'sessions/destroy', to: 'sessions#destroy', via: [:options]

  resources :checks, only: [:index, :create] do
    collection do
      get :credit
    end
  end

  resources :users do
    resources :oauth2, only: [:index, :destroy]
    resources :apps do
      member do
        put :update_secret
      end
    end
    resource :user_details, only: [:edit, :update]
    resources :topups,      only: [:show, :create, :edit, :update]
    resources :vouchers,    only: [:index, :create, :destroy] do
      collection do
        post :new_voucher
      end
    end
    resources :consumes,    only: [:create]

    resources :subscriptions

    member do
      get :validate_token
      put :validate_token_do
      get :resend_confirm_email
    end
  end

  resources :sessions, only: [:new, :create, :destroy] do
    collection do
      post :sign_with_grant
      get :password_lost
      post :password_lost_do
      get :get_token_password_lost
      post :check_token_password_lost
    end
  end

  root 'checks#index'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  mount StripeEvent::Engine => '/stripe-callbacks'
end

app/models/user.rb
# Attributes:
# - email: the user email
# - password_digest: user password encrypted with bcrypt
# - last_login_date: the timestamp of last login
# - admin: boolean, if the user is an admin
# - last_login_ip: the IP address of user's client used in last login
# Last two field is useful to have a unique token every time
# - password, password_confirmation: volatile attributes for singup and edit_user views
# - admin: boolean, if the user is a local admin
# - balance: user balance in pence (UKP x 100)
# - stripe_id: user id on Stripe
# - paypal_id: user id on Paypal
# - confirmed: boolean, if the user email was confirmed
# - confirm_token: email confirmation token
# - password_lost_token: the token to reset password
# - password_lost_token_expire: the token to reset password expiration
# - refresh_token: the token to request a new volatile token
# - refresh_token_expire: the expiration date of refresh token
#
# Relations:
# embeds_one UserDetail: all other information useful for invoicing services.
# embeds_many UserSocial: the link to social networks to provide a faster authentication (TODO)
# has_many App: the Application authorized by the user
#
# This class contains basic user data for authentication



class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActiveModel::SecurePassword

  before_create :create_confirm_token
  after_create  :add_local_app
  before_save   { self.email = email.downcase }

  field :email,                 type: String
  field :password_digest,       type: String
  field :last_login_date,       type: DateTime
  field :last_login_ip,         type: String
  field :admin,                 type: Boolean, default: false
  field :balance,               type: Integer, default: 0
  field :stripe_id,             type: String,  default: nil
  field :paypal_id,             type: String,  default: nil
  field :confirmed,             type: Boolean, default: false
  field :confirm_token,         type: String
  field :password_lost_token,   type: String
  field :password_lost_expire,  type: DateTime
  field :refresh_token,         type: String
  field :refresh_token_expire,  type: DateTime

  attr_accessor :stripe_token, :tk

  has_many :renew_tokens
  has_many :activities
  has_many :subscriptions

  embeds_one :user_detail

  validates :email, :presence => true,
            uniqueness: { case_sensitive: false }

  validates :password, length: { minimum: Settings.minimum_password_length }, :allow_nil => true

  validates_associated :user_detail, on: :update

  accepts_nested_attributes_for :user_detail

  # All methods for password verification are in this helper
  has_secure_password

  # Emulate has_many :trough
  def apps
    App.in(id: renew_tokens.map(&:app_id))
  end

  # update :last_login_date and :last_login_ip
  def touch_login(ip)
    self.update_attribute(:last_login_date, DateTime.now)
    self.update_attribute(:last_login_ip, ip)
    self.save
    self
  end

  # Generate the access_token in JWT format
  def generate_token(secret)
    JWT.encode(self.to_json,secret)
  end

  # store the access_token in a separate Redis Database
  def store_user_session_in_redis(secret, auto_renew)
    remember_token = generate_token(secret)
    $redis_user.set(remember_token,[self.id.to_s,auto_renew].to_json)
    $redis_user.expire(remember_token, Settings.token_expire)

    remember_token
  end

  # check if the user
  def is_admin?
    self.admin
  end

  # check if extra user data is complete
  def data_complete?
    if user_detail.nil?
      self.build_user_detail
      self.save
      false
    else
      if user_detail.name.blank? or user_detail.address1.blank? or user_detail.zip.blank? or user_detail.city.blank? or user_detail.state.blank? or user_detail.country.blank?
        false
      else
        true
      end
    end
  end

  # check if the user has confirmed his email
  def confirmed?
    self.confirmed
  end

  def create_password_lost_token
    o = [('a'..'z'), ('A'..'Z'), ('0'..'9')].map { |i| i.to_a }.flatten
    self.password_lost_token = (0...64).map{ o[rand(o.length)] }.join
    self.password_lost_expire = DateTime.now + 2.hours
    self.save
  end

  def set_refresh_tokens
    o = [('a'..'z'), ('A'..'Z'), ('0'..'9')].map { |i| i.to_a }.flatten
    self.refresh_token = (0...64).map{ o[rand(o.length)] }.join
    self.refresh_token_expire = DateTime.now + (Settings.renew_token_expire).to_i.days
    self.save
    self
  end

  def delete_refresh_token
    self.refresh_token = nil
    self.refresh_token_expire = DateTime.now
    self.save
  end

  private

  def create_confirm_token
    o = [('a'..'z'), ('A'..'Z'), ('0'..'9')].map { |i| i.to_a }.flatten
    self.confirm_token = (0...64).map{ o[rand(o.length)] }.join
  end

  def add_local_app
    if Settings.multi_application == 'false'
      RenewToken.create(user: self, app: nil)
    else
      RenewToken.create(user: self, app: App.where(name: Settings.local_app_name).first)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :show, :destroy]

  # Only for admin view
  def index
    if current_user.is_admin?
      @users = User.all.page(params[:page])
    else
      redirect_to root_path
    end
  end

  def show
    if current_user.is_admin?
      @user = User.find(params[:id])
      @activities = @user.activities.desc(:created_at).page(params[:page])
    else
      redirect_to root_path
    end
  end

  # Form for sign up
  def new
    @user = User.new
    @user.build_user_detail
  end

  # Create a new user and pre-fill empty user details
  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'Welcome! Your login details are successfully stored and in a few minutes you\'ll find a confirmation email in your inbox: please approve your registration as soon as possible. In the meantime, please provide other useful information for billing and contact you.'

      # if all is correct, send confirmation email...
      UserMailer.token_email(@user).deliver

      # ...sign-in user...
      sign_in(@user)

      # ...and redirect to user page, to request invoice data
      redirect_to edit_user_user_details_path(@user)
    else
      flash.now[:error]='We are unable to create your account'
      render 'new'

    end
  end

  # Edit user password form
  def edit
    @user = User.find(params[:id])
    unless @user.data_complete?
      redirect_to edit_user_user_details_path(@user)
    end
  end

  # Update user password
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = 'Your password has successfully updated'
      if @user.data_complete?
        redirect_to root_path
      else
        redirect_to edit_user_user_details_path(@user)
      end
    else
      flash.now[:error] = 'Error updating your password'
      render 'edit'
    end
  end

  # Destroy a user
  def destroy
    if current_user.is_admin?
      @user = User.find(params[:id])
      @user.destroy
      flash[:success]="User deleted"
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  # Form to validate token sended via E-Mail
  def validate_token
    @user=User.find(params[:id])
    if @user.confirmed?
      if @user.data_complete?
        redirect_to root_path
      else
        redirect_to edit_user_user_details_path(@user)
      end
    end
  end

  # Confirm user email
  def validate_token_do
    @user=User.find(params[:id])
    unless @user.confirmed?
      if @user.confirm_token == params[:user][:tk]
        @user.update_attribute(:confirmed, true)
        UserMailer.welcome(@user).deliver
      end
    end

    if @user.confirmed?
      flash[:success] = 'Your email has successfully confirmed'
      if @user.data_complete?
        redirect_to root_path
      else
        redirect_to edit_user_user_details_path(@user)
      end
    else
      flash.now[:error] = 'Invalid token'
      render :validate_token
    end
  end

  # Resend confirmation email
  def resend_confirm_email
    UserMailer.token_email(User.find(params[:id])).deliver
    flash[:success] = 'We have send you another mail with your token'
    redirect_to root_path
  end

  private

  # Strong params: permit only email, password and password confirmation
  def user_params
    params.require(:user).permit(:email, :password,
                                 :password_confirmation,
                                 :user_detail_attributes => [ :name ]
    )
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Update password for user <%=@user.user_detail.name%></h1>
<div class="row">
  <div class="span6 offset3">
    <%= simple_form_for @user do |f| %>
      <% if @user.user_detail.name.nil? or @user.user_detail.name.blank? %>
        <p>It's strange, but we don't remember your name...</p>
        <%= f.simple_fields_for :user_detail do |b| %>
          <div class="form-group">
            <%= b.input :name %>
          </div>
        <% end %>
      <% end %>

      <div class="form-group">
        <%= f.input :password, as: :pwdcalc_simple %>
      </div>

      <div class="form-group">
        <%= f.input :password_confirmation %>
      </div>

      <%= f.submit 'Update password', class: 'btn btn-large btn-primary' %>
    <% end %>
  </div>

  <%# pwdcalc_hints %>
</div>
<div class="row">
  <div class="span6 offset3">
    Unhappy? Destroy my account.
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="span12">
    <h3>Users</h3>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Email</th>
        <th>Name</th>
        <th>Registration Date</th>
        <th>Balance</th>
        <th>Total Top-Ups</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%=user.email%></td>
          <td><%=user.user_detail.name%></td>
          <td><%=user.created_at.strftime("%d/%m/%Y")%></td>
          <td><%= user.balance.to_f/100 %>£</td>
          <td><%= user.activities.where(kind: 'topup').sum(&:amount).to_f/100 %>£</td>
          <td>
            <%=link_to 'Show', user_path(user), class: 'btn btn-small btn-success'%>
            <%=link_to 'Destroy', user_path(user), method: :delete, class: 'btn btn-small btn-danger', data: { confirm: "Are you sure?" }%>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <%= paginate @users %>
  </div>
</div>

app/views/users/new.html.erb
<h1>User Registration</h1>
<div class="row">
  <div class="span6 offset3">
    <%= simple_form_for @user do |f| %>

      <%= f.simple_fields_for :user_detail do |b| %>
        <div class="form-group">
          <%= b.input :name %>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.input :email %>
      </div>

      <div class="form-group">
        <%= f.input :password, as: :pwdcalc_simple %>
      </div>

      <div class="form-group">
        <%= f.input :password_confirmation %>
      </div>

      <%= f.submit 'Register', class: 'btn btn-large btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <h1>This is the status of <%= @user.user_detail.name %></h1>
    <h2>His current balance is <%= @user.balance.to_f/100 %> £</h2>
    <div class="span8">
      <table class="table table-striped">
        <tr>
          <td>Name</td>
          <td><%=@user.user_detail.name%></td>
        </tr>
        <tr>
          <td>Address</td>
          <td>
            <%=@user.user_detail.address1%><br/>
            <%=@user.user_detail.address2%>
          </td>
        </tr>
        <tr>
          <td>Zip</td>
          <td><%=@user.user_detail.zip%></td>
        </tr>
        <tr>
          <td>City</td>
          <td><%=@user.user_detail.city%></td>
        </tr>
        <tr>
          <td>State</td>
          <td><%=@user.user_detail.state%></td>
        </tr>
        <tr>
          <td>Country</td>
          <td><%=@user.user_detail.country%></td>
        </tr>
        <tr>
          <td>Vat ID</td>
          <td><%=@user.user_detail.vat_id%></td>
        </tr>
        <tr>
          <td>Phone</td>
          <td><%=@user.user_detail.phone%></td>
        </tr>
        <tr>
          <td>Email</td>
          <td><%=@user.email%></td>
        </tr>
      </table>
    </div>
    <div class="span3">
      <h3>Last activities</h3>
      <ul style="text-align: left">
        <% @activities.each do |a| %>
          <li>
            <%=a.created_at.strftime("%d/%m/%Y")%>:
            <a href="<%= link_to_document(a) %>" data-toggle="tooltip" title="<%= tooltip_text(a) %>"><%= a.kind %></a>

            of <%=(a.amount.to_f/100).to_s%>£
          </li>
        <% end %>
      </ul>
      <%= paginate @activities %>
    </div>
  </div>
</div>

app/views/users/validate_token.html.erb
<h1>Validate token</h1>
<div class="row">
  <div class="span6 offset3">
    <%= simple_form_for @user, url: validate_token_do_user_path, method: :put do |f| %>

      <div class="form-group">
        <%= f.input :tk, label: 'Confirmation token', :input_html => { :value => params[:tk] } %>
      </div>

      <%= f.submit 'Confirm my email', class: 'btn btn-large btn-primary' %>
    <% end %>
    <p>Have you lost confirmation email? Check in your spam folder, or <%= link_to 'send another time', resend_confirm_email_user_path(@user) %></p>
  </div>
</div>