config/routes.rb
UsersMoydCo::Application.routes.draw do

  get  'oauth2/authorize'
  post 'oauth2/authorize'
  get  'oauth2/deny_authorize'
  get  'oauth2/allow_authorize'
  post 'oauth2/token',  to: 'oauth2#token_request'
  post 'oauth2/revoke'

  match 'checks/credit', to: 'checks#credit', via: [:options]
  match 'sessions/destroy', to: 'sessions#destroy', via: [:options]

  resources :checks, only: [:index, :create] do
    collection do
      get :credit
    end
  end

  resources :users do
    resources :oauth2, only: [:index, :destroy]
    resources :apps do
      member do
        put :update_secret
      end
    end
    resource :user_details, only: [:edit, :update]
    resources :topups,      only: [:show, :create, :edit, :update]
    resources :vouchers,    only: [:index, :create, :destroy] do
      collection do
        post :new_voucher
      end
    end
    resources :consumes,    only: [:create]

    resources :subscriptions

    member do
      get :validate_token
      put :validate_token_do
      get :resend_confirm_email
    end
  end

  resources :sessions, only: [:new, :create, :destroy] do
    collection do
      post :sign_with_grant
      get :password_lost
      post :password_lost_do
      get :get_token_password_lost
      post :check_token_password_lost
    end
  end

  root 'checks#index'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  mount StripeEvent::Engine => '/stripe-callbacks'
end

app/views/apps/index.html.erb
<h3>Apps activated</h3>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>client_id</th>
    <th>Uri</th>
    <th>Code</th>
    <th>Implicit</th>
    <th>Password</th>
    <th>AutoRenew</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @apps.each do |a| %>
    <tr>
      <td><%= a.name %></td>
      <td><%= a.id %></td>
      <td><%= a.url + a.path%></td>
      <td><%= 'X' if a.enable_code%></td>
      <td><%= 'X' if a.enable_implicit%></td>
      <td><%= 'X' if a.enable_password%></td>
      <td><%= 'X' if a.auto_renew%></td>
      <td><%= link_to 'Regenerate secret', update_secret_user_app_path(current_user,a), method: :put, class: 'btn btn-small btn-warning' %></td>
      <td>
        <% unless a.name == Settings.local_app_name %>
          <%= link_to 'Destroy', user_app_path(current_user,a), method: :delete, class: 'btn btn-small btn-danger', data: { confirm: "Are you sure?" } %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<h3>Generate App credentials</h3>
<%= simple_form_for(@app, url: user_apps_path(current_user), method: :post, html: {class: 'form-horizontal'}) do |f| %>
  <%= f.input :name %>
  <%= f.input :url %>
  <%= f.input :path %>
  <%= f.input :enable_code,     as: :boolean %>
  <%= f.input :enable_implicit, as: :boolean %>
  <%= f.input :enable_password, as: :boolean %>
  <%= f.input :auto_renew,      as: :boolean %>
  <%= f.submit 'Create App', class: 'btn btn-success' %>
<% end %>