config/routes.rb
UsersMoydCo::Application.routes.draw do

  get  'oauth2/authorize'
  post 'oauth2/authorize'
  get  'oauth2/deny_authorize'
  get  'oauth2/allow_authorize'
  post 'oauth2/token',  to: 'oauth2#token_request'
  post 'oauth2/revoke'

  match 'checks/credit', to: 'checks#credit', via: [:options]
  match 'sessions/destroy', to: 'sessions#destroy', via: [:options]

  resources :checks, only: [:index, :create] do
    collection do
      get :credit
    end
  end

  resources :users do
    resources :oauth2, only: [:index, :destroy]
    resources :apps do
      member do
        put :update_secret
      end
    end
    resource :user_details, only: [:edit, :update]
    resources :topups,      only: [:show, :create, :edit, :update]
    resources :vouchers,    only: [:index, :create, :destroy] do
      collection do
        post :new_voucher
      end
    end
    resources :consumes,    only: [:create]

    resources :subscriptions

    member do
      get :validate_token
      put :validate_token_do
      get :resend_confirm_email
    end
  end

  resources :sessions, only: [:new, :create, :destroy] do
    collection do
      post :sign_with_grant
      get :password_lost
      post :password_lost_do
      get :get_token_password_lost
      post :check_token_password_lost
    end
  end

  root 'checks#index'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  mount StripeEvent::Engine => '/stripe-callbacks'
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  # nothing than a default page
  def index
    if signed_in?
      if current_user.is_admin?

        begin
          @application_name = App.find(application_id).name
        rescue
          @application_name =  Settings.single_application_mode_name
        end

        dates = (1.month.ago.to_date..Date.today).map{ |date| date.strftime("%b %d") }

        user_subsctiptions=User.all.group_by {|d| d.created_at.to_date}
        users = (1.month.ago.to_date..Date.today).map{ |date| user_subsctiptions[date].nil? ? 0 : user_subsctiptions[date].count }

        user_topups=Activity.where(kind: 'topup').group_by {|d| d.created_at.to_date}
        topups = (1.month.ago.to_date..Date.today).map{ |date| user_topups[date].nil? ? 0 : user_topups[date].sum(&:amount).to_f/100 }

        @chart = LazyHighCharts::HighChart.new('graph') do |f|
          f.title(:text => 'User Registration vs Topup in last month')
          f.xAxis(:categories => dates)
          f.series(:name => 'New users', :yAxis => 0, :data => users)
          f.series(:name => 'Top-ups in UKP', :yAxis => 1, :data => topups)

          f.yAxis [
                      {:title => {:text => 'New users', :margin => 70} },
                      {:title => {:text => 'Top-ups in UKP'}, :opposite => true},
                  ]

          f.legend(:align => 'right', :verticalAlign => 'top', :y => 75, :x => -50, :layout => 'vertical',)
          f.chart({:defaultSeriesType=>'column'})
        end

        @top_up_to_bill = Activity.where(kind: 'topup').reject {|r| !r.invoice.nil?}
      else
        @name = current_user.user_detail.name || current_user.email
        @activities = current_user.activities.desc(:created_at).page(params[:page])
        @voucher = Voucher.new
        @amount = params[:amount]
      end
    else
      redirect_to signin_path
    end
  end

  # check if the user is authenticated, by token
  def create
    if signed_in?
      render text: 'OK', status: 200
    else
      render text: 'Error', status: 401
    end
  end

  def credit
    if signed_in?
      render text: current_user.balance, status: 200
    else
      render text: 'Error', status: 401
    end
  end

end

app/helpers/checks_helper.rb
module ChecksHelper
  # For topup, link the show invoice or upload invoice
  def link_to_document(activity)
    if activity.kind == 'topup'
      if current_user.is_admin?
        edit_user_topup_path(activity.user,activity.id)
      else
        user_topup_path(current_user,activity.id)
      end
    elsif activity.kind == 'voucher'
      '#'
    elsif activity.kind == 'consume'
      '#'
    end
  end

  # Tooltip text for user activity list
  def tooltip_text(activity)
    if activity.kind == 'topup'
      if current_user.is_admin?
        'Click me to upload invoice'
      else
        'Click me to download invoice'
      end
    elsif activity.kind == 'voucher'
      "This voucher was emitted on #{activity.voucher.created_at}. The amount of #{(activity.amount.to_f/100).to_s} UKP has been credited on #{activity.created_at}" unless activity.voucher.nil?
    elsif activity.kind == 'consume'
      "The consumption is referred to #{activity.consume.description}"  unless activity.consume.nil?
    end
  end
end

app/views/checks/index.html.erb
<% if signed_in? %>
  <% if current_user.is_admin? %>
    <div class="row">
      <div class="span12">

        <%= high_chart('user_vs_topup_chart', @chart) %>
      </div>
    </div>
    <div class="row">
      <div class="span12">
        <h3>Top-Up without a linked invoice</h3>
        <table class="table table-striped">
          <thead>
          <tr>
            <th>Date</th>
            <th>User to be billed</th>
            <th>Amount</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          <% @top_up_to_bill.each do |a| %>
            <tr>
              <td><%=a.created_at.strftime("%d/%m/%Y")%></td>
              <td>
                <%= a.user.user_detail.name %> -
                <%= a.user.user_detail.address1 %> -
                <%= a.user.user_detail.address2 %> -
                <%= a.user.user_detail.zip %> -
                <%= a.user.user_detail.city %> -
                <%= a.user.user_detail.state %> -
                <%= a.user.user_detail.country %> -
                <%= a.user.user_detail.vat_id %>
              </td>
              <td><%=(a.amount.to_f/100).to_s%></td>
              <td>
                <a href="<%= link_to_document(a) %>" data-toggle="tooltip" title="<%= tooltip_text(a) %>" class="btn btn-success btn-small">Create Invoice</a>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>

  <% else %>
    <div class="container">
      <div class="row">
        <h1>Hello, <%= @name %></h1>
        <h2>Your current balance is <%= current_user.balance.to_f/100 %> £</h2>
        <div class="span8">
          <div class="row">
            <div class="span6 shadow">
              <h3>Have you a voucher?</h3>
              <h5>Insert your code here!</h5>
              <%= simple_form_for @voucher, url: user_vouchers_path(current_user) do |f| %>
                <%=f.input :voucher_code%><br/>
                <%=submit_tag('Activate it!', class: 'btn btn-large btn-primary')%>
              <% end %>
              <p><i><%=link_to('How can I get that?','#')%></i></p>
            </div>
          </div>
          <div class="row">
            <div class="span2 shadow">
              <h3>Top-up 10 £</h3>
              <h5>(vat incl.)</h5>
              <%= form_tag user_topups_path(current_user) do %>
                <script
                src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= STRIPE_PUBLIC_KEY %>"
                data-amount="1000"
                data-name="<%= @application_name %>"
                data-description="TopUp of 10.00 UKP"
                data-currenncy="gbp"
                data-email="<%= current_user.email %>"
                >
                </script>
                <%= hidden_field_tag :amount, 1000 %>
              <% end %>
            </div>

            <div class="span2 shadow">
              <h3>Top-up 25 £</h3>
              <h5>(vat incl.)</h5>
              <%= form_tag user_topups_path(current_user) do %>
                <script
                src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= STRIPE_PUBLIC_KEY %>"
                data-amount="2500"
                data-name="<%= @application_name %>"
                data-description="TopUp of 25.00 UKP"
                data-currenncy="gbp"
                data-email="<%= current_user.email %>"
                >
                </script>
                <%= hidden_field_tag :amount, 2500 %>
              <% end %>
            </div>

            <div class="span2 shadow">
              <h3>Top-up 50 £</h3>
              <h5>(vat incl.)</h5>
              <%= form_tag user_topups_path(current_user) do %>
                <script
                src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= STRIPE_PUBLIC_KEY %>"
                data-amount="5000"
                data-name="<%= @application_name %>"
                data-description="TopUp of 50.00 UKP"
                data-currenncy="gbp"
                data-email="<%= current_user.email %>"
                >
                </script>
                <%= hidden_field_tag :amount, 5000 %>
              <% end %>
            </div>
          </div>

          <div class="row">
            <div class="span2 shadow">
              <h3>Top-up 100 £</h3>
              <h5>(vat incl.)</h5>
              <%= form_tag user_topups_path(current_user) do %>
                <script
                src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= STRIPE_PUBLIC_KEY %>"
                data-amount="10000"
                data-name="<%= @application_name %>"
                data-description="TopUp of 100.00 UKP"
                data-currenncy="gbp"
                data-email="<%= current_user.email %>"
                >
                </script>
                <%= hidden_field_tag :amount, 10000 %>
              <% end %>
            </div>

            <div class="span2 shadow">
              <h3>Top-up 200 £</h3>
              <h5>(vat incl.)</h5>
              <%= form_tag user_topups_path(current_user) do %>
                <script
                src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= STRIPE_PUBLIC_KEY %>"
                data-amount="20000"
                data-name="<%= @application_name %>"
                data-description="TopUp of 200.00 UKP"
                data-currenncy="gbp"
                data-email="<%= current_user.email %>"
                >
                </script>
                <%= hidden_field_tag :amount, 20000 %>
              <% end %>
            </div>

            <div class="span2 shadow">
              <h3>Top-up 500 £</h3>
              <h5>(vat incl.)</h5>
              <%= form_tag user_topups_path(current_user) do %>
                <script
                src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= STRIPE_PUBLIC_KEY %>"
                data-amount="50000"
                data-name="<%= @application_name %>"
                data-description="TopUp of 500.00 UKP"
                data-currenncy="gbp"
                data-email="<%= current_user.email %>"
                >
                </script>
                <%= hidden_field_tag :amount, 50000 %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="span3 shadow">
          <h3>Last activities</h3>
          <ul style="text-align: left">
            <% @activities.each do |a| %>
              <li>
                <%=a.created_at.strftime("%d/%m/%Y")%>:
                <a href="<%= link_to_document(a) %>" data-toggle="tooltip" title="<%= tooltip_text(a) %>"><%= a.kind %></a>

                of <%=(a.amount.to_f/100).to_s%>£
              </li>
            <% end %>
          </ul>
          <%= paginate @activities %>
        </div>
      </div>


    </div>

  <% end %>
<% else %>
  <%=link_to('Login', signin_path) %> | <%= link_to('Register', signup_path) %>
<% end %>