config/routes.rb
UsersMoydCo::Application.routes.draw do

  get  'oauth2/authorize'
  post 'oauth2/authorize'
  get  'oauth2/deny_authorize'
  get  'oauth2/allow_authorize'
  post 'oauth2/token',  to: 'oauth2#token_request'
  post 'oauth2/revoke'

  match 'checks/credit', to: 'checks#credit', via: [:options]
  match 'sessions/destroy', to: 'sessions#destroy', via: [:options]

  resources :checks, only: [:index, :create] do
    collection do
      get :credit
    end
  end

  resources :users do
    resources :oauth2, only: [:index, :destroy]
    resources :apps do
      member do
        put :update_secret
      end
    end
    resource :user_details, only: [:edit, :update]
    resources :topups,      only: [:show, :create, :edit, :update]
    resources :vouchers,    only: [:index, :create, :destroy] do
      collection do
        post :new_voucher
      end
    end
    resources :consumes,    only: [:create]

    resources :subscriptions

    member do
      get :validate_token
      put :validate_token_do
      get :resend_confirm_email
    end
  end

  resources :sessions, only: [:new, :create, :destroy] do
    collection do
      post :sign_with_grant
      get :password_lost
      post :password_lost_do
      get :get_token_password_lost
      post :check_token_password_lost
    end
  end

  root 'checks#index'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  mount StripeEvent::Engine => '/stripe-callbacks'
end

app/views/layouts/_flashes.html.erb
<% unless flash[:notice].blank? %>
  <div class="alert alert-success">
    <%= content_tag :div, flash[:notice] %>
  </div>
<% end %>

<% unless flash[:success].blank? %>
  <div class="alert alert-success">
    <%= content_tag :div, flash[:success] %>
  </div>
<% end %>

<% unless flash[:error].blank? %>
  <div class="alert alert-danger">
    <%= content_tag :div, flash[:error] %>
  </div>
<% end %>

<% unless flash[:alert].blank? %>
  <div class="alert alert-info">
    <%= content_tag :div, flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<%= debug(params) if Rails.env.development?%>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%
        begin
          app_name = App.find(application_id).name
          app_url  = App.find(application_id).name
        rescue
          app_name = Settings.single_application_mode_name
          app_url  = Settings.single_application_mode_url
        end

        if app_name == Settings.local_app_name
          app_name = 'Account admin'
          app_url  = root_path
        end
      %>

      <%= link_to app_name, app_url, id: 'logo' %>

      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
            <% unless current_user.confirmed? %>
              <li><%= link_to 'Confirm my email', validate_token_user_path(current_user) %></li>
            <% end %>
            <li><%= link_to 'Edit User Details',  edit_user_user_details_path(current_user) %></li>
            <% if current_user.data_complete? %>
              <li><%= link_to 'Change Password',  edit_user_path(current_user) %></li>
            <% end %>
            <% unless current_user.is_admin? %>
              <li><%= link_to 'Subscription', user_subscriptions_path(current_user) %></li>
            <% end %>
            <li><%= link_to 'Linked application', user_oauth2_index_path(current_user) %></li>
            <li><%= link_to 'Logout',             signout_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to 'Login',        signin_path %></li>
            <li><%= link_to 'Register',     signup_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_subnav.html.erb
<% if signed_in? and current_user.is_admin?%>
  <ul class="nav nav-tabs nav-tabs-justified">
    <li <%= 'class=active' if controller_name =='checks'%>><%=link_to 'Home', root_path %></li>
    <li <%= 'class=active' if controller_name =='users'%>><%=link_to 'Users', users_path %></li>
    <li <%= 'class=active' if controller_name =='subscriptions'%>><%= link_to 'Subscription', user_subscriptions_path(current_user) %></li>
    <% if Settings.multi_application == 'true' %>
      <li <%= 'class=active' if controller_name =='apps'%>><%=link_to 'Apps', user_apps_path(current_user) %></li>
    <% end %>
    <li <%= 'class=active' if controller_name =='vouchers'%>><%=link_to 'Vouchers', user_vouchers_path(current_user) %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="msvalidate.01" content="FE15DE16FAA7CC4007F6F52D2ACDF98E" />

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <%# if Settings.billing_provider == 'stripe' %>
    <%# javascript_include_tag "https://js.stripe.com/v1/", "application" %>
    <%# tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%# end %>

  <%= csrf_meta_tags %>
  <link href="/assets/favicon.ico" rel="shortcut icon"/>
</head>
<body>

<%= render 'layouts/header' unless controller_name == 'sessions' and (action_name == 'new' or action_name == 'create' ) %>
<%= render 'layouts/flashes' %>
<div class="container">
  <%= render 'layouts/subnav'  unless controller_name == 'sessions' and (action_name == 'new' or action_name == 'create' ) %>
  <%= yield %>
</div>
<div class="container-narrow">
  <div class="page-footer">
    <%= render 'layouts/footer'  unless controller_name == 'sessions' and (action_name == 'new' or action_name == 'create' )%>
  </div>
</div>

</body>
</html>